"use client";

import type { Metadata } from "next";
import React, { createContext } from "react";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/lib/registry";
import { ThemeProvider } from "styled-components";
import { RecoilRoot, atom } from "recoil";

// export const metadata: Metadata = {
//   title: "backgammon.js",
//   description: "Generated by create next app",
// };

const defaultValue = {
  theme: "light",
  onChangeTheme: () => {},
};

// export const CustomThemeContext = React.createContext(defaultValue);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StyledComponentsRegistry>
      <RecoilRoot>
        <html lang="en">
          <body>
            <Header />
            {children}
          </body>
        </html>
      </RecoilRoot>
    </StyledComponentsRegistry>
  );
}
