import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
  title: "backgammon.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
