import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Header from "@/components/Header";
import { styled } from "styled-components";

export const metadata: Metadata = {
  title: "Backgammon.JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
